import type { Property } from "./types";
import { img } from "./propertyImages";

export const properties: Property[] = [
  {
    slug: "the-parkview-thonglor-3502",
    ownerId: "owner-1",
    tier: 1,
    name: "The Parkview Thonglor",
    type: "คอนโด",
    address: "สุขุมวิท 55, คลองตันเหนือ",
    district: "ทองหล่อ",
    mapUrl: null,
    status: "Available",
    salePrice: 8900000,
    rentPrice: 38000,
    areaSqm: 42,
    bedrooms: 1,
    bathrooms: 1,
    floor: "18",
    facing: "ทิศตะวันออก",
    images: [img.condoTower1, img.livingRoom, img.bedroom, img.kitchen],
    commonFeePerSqm: 65,
    avgRentInArea: 36000,
    transferFeeEstimate: 89000,
    transit: [{ station: "ทองหล่อ", line: "BTS", distanceMeters: 350 }],
    investor: {
      roiPercent: 5.1,
      rentalYieldPercent: 5.1,
      occupancyPercent: 92,
      cashflowPerMonth: 8200,
    },
    description:
      "คอนโดใจกลางทองหล่อ ใกล้ BTS เดินถึง ตกแต่งสไตล์โมเดิร์น เหมาะสำหรับอยู่เองหรือปล่อยเช่า",
  },
  {
    slug: "baan-sivalai-ramintra-129",
    ownerId: "owner-2",
    tier: 2,
    name: "บ้านศิวาลัย รามอินทรา",
    type: "บ้าน",
    address: "รามอินทรา กม.10",
    district: "คันนายาว",
    mapUrl: null,
    status: "Available",
    salePrice: 6500000,
    rentPrice: null,
    areaSqm: 180,
    bedrooms: 4,
    bathrooms: 3,
    floor: "2 ชั้น",
    facing: "ทิศใต้",
    images: [img.houseExterior1, img.backyardPatio, img.bedroom, img.kitchen],
    commonFeePerSqm: 0,
    avgRentInArea: 28000,
    transferFeeEstimate: 65000,
    transit: [{ station: "วัดพระศรีมหาธาตุ", line: "BTS", distanceMeters: 4200 }],
    investor: {
      roiPercent: 4.2,
      rentalYieldPercent: 4.4,
      occupancyPercent: 85,
      cashflowPerMonth: 6100,
    },
    description:
      "บ้านเดี่ยวหลังมุม พื้นที่ใช้สอยกว้างขวาง เหมาะสำหรับครอบครัว ใกล้โรงเรียนนานาชาติและห้างสรรพสินค้า",
  },
  {
    slug: "noble-around-ari-0812",
    ownerId: "owner-1",
    tier: 1,
    name: "Noble Around Ari",
    type: "คอนโด",
    address: "พหลโยธิน ซอย 7",
    district: "อารีย์",
    mapUrl: null,
    status: "Reserved",
    salePrice: 12500000,
    rentPrice: 48000,
    areaSqm: 55,
    bedrooms: 2,
    bathrooms: 2,
    floor: "24",
    facing: "ทิศเหนือ",
    images: [img.condoTower2, img.livingRoom, img.bedroom, img.kitchen],
    commonFeePerSqm: 75,
    avgRentInArea: 45000,
    transferFeeEstimate: 125000,
    transit: [{ station: "อารีย์", line: "BTS", distanceMeters: 180 }],
    investor: {
      roiPercent: 4.6,
      rentalYieldPercent: 4.6,
      occupancyPercent: 90,
      cashflowPerMonth: 9800,
    },
    description:
      "ห้องมุม วิวเปิดโล่ง ทำเลอารีย์แหล่งไลฟ์สไตล์ยอดนิยม เดินเข้า BTS ได้ทันที",
  },
  {
    slug: "townplus-bangna-km7-2201",
    ownerId: "owner-2",
    tier: 2,
    name: "Town Plus บางนา กม.7",
    type: "ทาวน์โฮม",
    address: "บางนา-ตราด กม.7",
    district: "บางนา",
    mapUrl: null,
    status: "Available",
    salePrice: 4200000,
    rentPrice: 18000,
    areaSqm: 120,
    bedrooms: 3,
    bathrooms: 2,
    floor: "3 ชั้น",
    facing: "ทิศตะวันตก",
    images: [img.townhouseStreet, img.livingRoom, img.bedroom, img.kitchen],
    commonFeePerSqm: 35,
    avgRentInArea: 17000,
    transferFeeEstimate: 42000,
    transit: [{ station: "แบริ่ง", line: "BTS", distanceMeters: 5100 }],
    investor: {
      roiPercent: 4.9,
      rentalYieldPercent: 5.1,
      occupancyPercent: 88,
      cashflowPerMonth: 5400,
    },
    description:
      "ทาวน์โฮมสไตล์โมเดิร์น 3 ชั้น ใกล้ทางด่วนและเมกาบางนา เหมาะสำหรับครอบครัวรุ่นใหม่",
  },
  {
    slug: "land-bangkok-ratchada-plot-410",
    ownerId: "owner-3",
    tier: 1,
    name: "ที่ดินเปล่า ถนนรัชดาภิเษก",
    type: "ที่ดิน",
    address: "ถนนรัชดาภิเษก ใกล้ห้วยขวาง",
    district: "ห้วยขวาง",
    mapUrl: null,
    status: "Available",
    salePrice: 45000000,
    rentPrice: null,
    areaSqm: 400,
    bedrooms: 0,
    bathrooms: 0,
    floor: "-",
    facing: "ทิศตะวันออก",
    images: [img.landAerial1, img.landAerial2],
    commonFeePerSqm: 0,
    avgRentInArea: 0,
    transferFeeEstimate: 450000,
    transit: [{ station: "ห้วยขวาง", line: "MRT", distanceMeters: 650 }],
    investor: {
      roiPercent: 3.8,
      rentalYieldPercent: 0,
      occupancyPercent: 0,
      cashflowPerMonth: 0,
    },
    description:
      "ที่ดินแปลงสวย ผังเมืองสีแดง เหมาะสำหรับพัฒนาโครงการเชิงพาณิชย์ ใกล้ MRT ห้วยขวาง",
  },
  {
    slug: "the-lumpini-24-1904",
    ownerId: "owner-1",
    tier: 2,
    name: "The Lumpini 24",
    type: "คอนโด",
    address: "สุขุมวิท 24",
    district: "คลองตัน",
    mapUrl: null,
    status: "For Rent",
    salePrice: null,
    rentPrice: 32000,
    areaSqm: 38,
    bedrooms: 1,
    bathrooms: 1,
    floor: "19",
    facing: "ทิศใต้",
    images: [img.condoTower3, img.bedroom, img.livingRoom, img.kitchen],
    commonFeePerSqm: 70,
    avgRentInArea: 33000,
    transferFeeEstimate: 0,
    transit: [{ station: "พร้อมพงษ์", line: "BTS", distanceMeters: 420 }],
    investor: {
      roiPercent: 0,
      rentalYieldPercent: 0,
      occupancyPercent: 95,
      cashflowPerMonth: 0,
    },
    description:
      "ห้องพร้อมเข้าอยู่ ตกแต่งครบ ใกล้ EmQuartier และ BTS พร้อมพงษ์ เดินทางสะดวก",
  },
  {
    slug: "baan-panya-indra-rangsit-88",
    ownerId: "owner-3",
    tier: 3,
    name: "บ้านปัญญาอินทรา รังสิต",
    type: "บ้าน",
    address: "คลองสี่ ธัญบุรี",
    district: "รังสิต",
    mapUrl: null,
    status: "Available",
    salePrice: 3450000,
    rentPrice: 15000,
    areaSqm: 145,
    bedrooms: 3,
    bathrooms: 2,
    floor: "2 ชั้น",
    facing: "ทิศเหนือ",
    images: [img.houseExterior2, img.backyardPatio, img.bedroom, img.kitchen],
    commonFeePerSqm: 20,
    avgRentInArea: 14000,
    transferFeeEstimate: 34500,
    transit: [{ station: "รังสิต", line: "ARL", distanceMeters: 3800 }],
    investor: {
      roiPercent: 4.7,
      rentalYieldPercent: 5.2,
      occupancyPercent: 82,
      cashflowPerMonth: 4300,
    },
    description:
      "บ้านหลังใหม่ในโครงการรั้วรอบขอบชิด สวนส่วนกลาง ใกล้มหาวิทยาลัยและตลาดรังสิต",
  },
  {
    slug: "ideo-mobi-sukhumvit-eastpoint-2105",
    ownerId: "owner-2",
    tier: 3,
    name: "Ideo Mobi Sukhumvit Eastpoint",
    type: "คอนโด",
    address: "สุขุมวิท 64",
    district: "พระโขนง",
    mapUrl: null,
    status: "Sold",
    salePrice: 4650000,
    rentPrice: 16500,
    areaSqm: 28,
    bedrooms: 1,
    bathrooms: 1,
    floor: "21",
    facing: "ทิศตะวันตก",
    images: [img.condoTower1, img.bedroom, img.kitchen, img.livingRoom],
    commonFeePerSqm: 55,
    avgRentInArea: 15500,
    transferFeeEstimate: 46500,
    transit: [{ station: "พระโขนง", line: "BTS", distanceMeters: 280 }],
    investor: {
      roiPercent: 4.3,
      rentalYieldPercent: 4.3,
      occupancyPercent: 90,
      cashflowPerMonth: 3100,
    },
    description:
      "ห้องสตูดิโอขนาดกะทัดรัด ใกล้ BTS พระโขนง เหมาะสำหรับนักลงทุนปล่อยเช่า",
  },
  {
    slug: "townplus-watcharaphon-3306",
    ownerId: "owner-3",
    tier: 3,
    name: "Town Plus วัชรพล",
    type: "ทาวน์โฮม",
    address: "วัชรพล-รามอินทรา",
    district: "สายไหม",
    mapUrl: null,
    status: "Available",
    salePrice: 3890000,
    rentPrice: null,
    areaSqm: 110,
    bedrooms: 3,
    bathrooms: 2,
    floor: "3 ชั้น",
    facing: "ทิศตะวันออก",
    images: [img.houseExterior2, img.livingRoom, img.bedroom, img.kitchen],
    commonFeePerSqm: 30,
    avgRentInArea: 16500,
    transferFeeEstimate: 38900,
    transit: [{ station: "วัดพระศรีมหาธาตุ", line: "BTS", distanceMeters: 3600 }],
    investor: {
      roiPercent: 4.5,
      rentalYieldPercent: 4.8,
      occupancyPercent: 84,
      cashflowPerMonth: 4700,
    },
    description:
      "ทาวน์โฮมหน้ากว้าง ตกแต่งพร้อมอยู่ ใกล้ตลาดวัชรพลและถนนวงแหวนรอบนอก",
  },
  {
    slug: "the-esse-asoke-4801",
    ownerId: "owner-1",
    tier: 1,
    name: "The Esse Asoke",
    type: "คอนโด",
    address: "สุขุมวิท 21 (อโศก)",
    district: "อโศก",
    mapUrl: null,
    status: "Available",
    salePrice: 15900000,
    rentPrice: 55000,
    areaSqm: 48,
    bedrooms: 1,
    bathrooms: 1,
    floor: "35",
    facing: "ทิศตะวันออกเฉียงใต้",
    images: [img.condoTower3, img.livingRoom, img.kitchen, img.bedroom],
    commonFeePerSqm: 90,
    avgRentInArea: 52000,
    transferFeeEstimate: 159000,
    transit: [{ station: "อโศก", line: "BTS", distanceMeters: 150 }],
    investor: {
      roiPercent: 4.2,
      rentalYieldPercent: 4.2,
      occupancyPercent: 93,
      cashflowPerMonth: 11500,
    },
    description:
      "ตึกหรูใจกลางอโศก เชื่อมต่อ BTS และ MRT เพียงไม่กี่ก้าว วิวเมืองระดับพรีเมียม",
  },
];

export function getPropertyBySlug(slug: string): Property | undefined {
  return properties.find((p) => p.slug === slug);
}

export const propertyTypes = ["คอนโด", "บ้าน", "ทาวน์โฮม", "ที่ดิน"] as const;

export const districts = Array.from(new Set(properties.map((p) => p.district)));
